version: '3'

networks:
  game_at_15:

services:
  nginx:
    image: nginx:1.9
    container_name: nginx
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ../.:/var/www/data:delegated
    ports:
    - 80:80
    - 443:443
    depends_on:
    - php
    - postgres
    networks:
    - game_at_15
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    volumes:
    - ../.:/var/www/data
    ports:
    - 9000:9000
    networks:
    - game_at_15
  postgres:
    container_name: postgres
    image: "postgres:12.2"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4aWvh75t
      PGDATA: /data/postgres
    volumes:
      - ./postgres/data:/data/postgres
      - ./postgres/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
    - game_at_15
    restart: unless-stopped
  npm:
    container_name: npm
    image: "node:14.15.4"
    entrypoint: ['npm']
    working_dir: /home/node/app
    volumes:
      - ../.:/home/node/app
    networks:
    - game_at_15
  npx:
    container_name: npx
    image: "node:14.15.4"
    entrypoint: ['npx']
    working_dir: /home/node/app
    volumes:
      - ../.:/home/node/app
    networks:
    - game_at_15
